const { JSDOM, VirtualConsole } = require('jsdom');
const { test } = require('node:test');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { webcrypto } = require('node:crypto');
const html = fs.readFileSync(path.join(__dirname, '../dist/index.html'), 'utf8');
const bundle = fs.readFileSync(path.join(__dirname, '../dist/main.js'), 'utf8');
const errors = [];
const virtualConsole = new VirtualConsole();
virtualConsole.on('jsdomError', error => errors.push(error.message));
const id = '11111111-1111-4111-8111-111111111111';
const cacheKey = 'todo-personal:local:' + id, draftKey = 'todo-personal:entry-draft:' + id;
const wait = () => new Promise(resolve => setTimeout(resolve, 100));
function boot(entries, native = false) {
 const dom = new JSDOM(html, { url: 'https://test.local/', runScripts: 'outside-only', virtualConsole });
 const w = dom.window;
 Object.defineProperty(w, 'crypto', { value: webcrypto });
 Object.assign(w, { TextEncoder, TextDecoder, fetch: async () => { throw new TypeError('Network unavailable'); }, Request, Response, Headers });
 if (native) w.androidBridge = { postMessage() {} };
 for (const [key, value] of entries) w.localStorage.setItem(key, value);
 w.eval(bundle);
 return dom;
}
test('mobile notebook core flows persist across offline restart', async () => {
 const exp = Math.floor(Date.now() / 1000) + 86400;
 const jwt = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url') + '.' + Buffer.from(JSON.stringify({ sub: id, exp, role: 'authenticated' })).toString('base64url') + '.test';
 const seed = [['sb-ihvwqqvndmwtislvgamd-auth-token', JSON.stringify({ access_token: jwt, refresh_token: 'test-only', expires_at: exp, expires_in: 86400, token_type: 'bearer', user: { id, email: 'test@example.com', aud: 'authenticated', role: 'authenticated' } })], [cacheKey, JSON.stringify({ schemaVersion: 1, state: { todos: { home: [], today: [], week: [] }, notes: [] }, revision: 0, dirty: false, savedAt: new Date().toISOString() })]];
 let dom = boot(seed);
 const doc = () => dom.window.document;
 const click = selector => { assert.ok(doc().querySelector(selector), selector); doc().querySelector(selector).click(); };
 const input = (selector, value) => { const el = doc().querySelector(selector); el.value = value; el.dispatchEvent(new dom.window.Event('input', { bubbles: true })); };
 const disk = () => JSON.parse(dom.window.localStorage.getItem(cacheKey));
 const snapshot = () => Array.from({ length: dom.window.localStorage.length }, (_, i) => { const key = dom.window.localStorage.key(i); return [key, dom.window.localStorage.getItem(key)]; });
 try {
  await wait();
  assert.equal(doc().querySelector('#todo-app').hidden, false);
  assert.equal(doc().querySelector('[data-view="today"]').getAttribute('aria-current'), 'page');
  click('.mn-add');
  const selectedDates = () => Array.from(doc().querySelectorAll('[data-date][aria-pressed="true"]'), b => b.dataset.date);
  assert.deepEqual(selectedDates(), ['none']);
  click('[data-date="tomorrow"]');
  assert.deepEqual(selectedDates(), ['tomorrow']);
  input('[name="date"]', '2099-01-01');
  assert.deepEqual(selectedDates(), []);
  click('[data-date="none"]');
  assert.deepEqual(selectedDates(), ['none']);
  input('#mn-text', 'Deutsch 日本語 中文 — купить продукты');
  click('[data-date="today"]');
  assert.deepEqual(selectedDates(), ['today']);
  input('[name="time"]', '18:00');
  click('[data-save]');
  assert.equal(disk().state.todos.home[0].name, 'Deutsch 日本語 中文 — купить продукты');
  assert.equal(disk().state.todos.home[0].time, '18:00');
  assert.ok(doc().querySelector('.mn-card'));
  click('[data-open]');
  assert.deepEqual(selectedDates(), ['today']);
  input('#mn-text', 'Изменённая запись');
  assert.equal(disk().state.todos.home[0].name, 'Изменённая запись', 'existing entry autosaves');
  click('[data-back]');
  click('[data-check]');
  assert.equal(disk().state.todos.home[0].checked, true);
  click('[data-view="done"]');
  assert.equal(doc().querySelector('.mn-title').textContent, 'Изменённая запись');
  click('[data-check]');
  assert.equal(disk().state.todos.home[0].checked, false);
  click('[data-view="today"]');
  click('.mn-add');
  click('[data-type="note"]');
  input('#mn-text', 'Русский · English · Italiano · Español 😀');
  click('[data-back]');
  assert.ok(dom.window.localStorage.getItem(draftKey));
  const saved = snapshot();dom.window.close();dom = boot(saved);await wait();
  click('.mn-add');
  assert.equal(doc().querySelector('#mn-text').value, 'Русский · English · Italiano · Español 😀');
  click('[data-save]');
  assert.equal(disk().state.notes[0].title, 'Русский · English · Italiano · Español 😀');
  assert.equal(dom.window.localStorage.getItem(draftKey), null);
  click('[data-view="all"]');
  input('#mn-search', 'Español');
  assert.equal(doc().querySelectorAll('.mn-card').length, 1);
  click('[data-open]');click('[data-delete]');
  assert.equal(disk().state.notes.length, 0);
  click('[data-undo]');
  assert.equal(disk().state.notes.length, 1);
  input('#mn-search', '');
  click('.mn-add');input('#mn-text', 'Задача без срока');click('[data-save]');
  assert.equal(disk().state.todos.home[1].date, '');
  click('.mn-add'); input('#mn-text', 'Сохранить после освобождения места');
  const nativeSetItem = dom.window.Storage.prototype.setItem;
  dom.window.Storage.prototype.setItem = function () { throw new Error('Quota exceeded'); };
  click('[data-save]');
  assert.ok(doc().querySelector('#mn-text'), 'failed save keeps the editor open');
  assert.match(doc().querySelector('.mn-message').textContent, /Не удалось сохранить/);
  dom.window.Storage.prototype.setItem = nativeSetItem;
  click('[data-save]');
  assert.equal(disk().state.todos.home.length, 3, 'retry does not duplicate the entry');
  assert.equal(dom.window.localStorage.getItem(draftKey), null);
  click('[data-view="settings"]');
  assert.match(doc().querySelector('.mn-setting').textContent, /test@example.com/);
  const expired = snapshot().map(([key, value]) => {
   if (key !== 'sb-ihvwqqvndmwtislvgamd-auth-token') return [key, value];
   const session = JSON.parse(value); session.expires_at = 1;
   return [key, JSON.stringify(session)];
  });
  dom.window.close(); dom = boot(expired, true); await wait();
  assert.equal(doc().querySelector('#todo-app').hidden, false, 'native cold start works while expired session refresh cannot reach the network');
  assert.ok(doc().querySelector('.mobile-notebook'));
  assert.deepEqual(errors, []);
  console.log('PASS: mobile Today/create/edit/complete/restore/search/delete/undo, Unicode draft restart, optional deadline and account display; network unavailable, no JS errors.');
 } finally { dom.window.close(); }
});
